/** A QR code generated on the server (see lib/qr), with a label for screen readers. */
export function Qr({ svg, label }: { svg: string; label: string }) {
  return (
    <div
      role="img"
      aria-label={label}
      className="size-44 overflow-hidden rounded-lg border border-line bg-white p-2 [&>svg]:size-full"
      // Generated by the qrcode library from our own URL.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
